### ISSUE TITLE
Adding Openshift Metrics Deployment

### ISSUE THREAD

**Issue by stobias123** [hawkular/hawkular-grafana-datasource#59] opened 2017-02-23 00:56 UTC
I'm trying to add my openshift metrics deployment and I'm getting internal HTTP server errors.
I'm using self signed certs, checkbox for "CA certs" is checked and I'm using proxy mode.

Any help would be appreciated, I'd love to get dashboards for our origin apps. 

```
00:42:07,206 ERROR [org.hawkular.metrics.api.jaxrs.util.ApiUtils] (RxComputationScheduler-1) HAWKMETRICS200010: Failed to process request: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
```

**Comment by jsanda** [comment] 2017-02-23 03:40
I am assuming that Hawkular Metrics and Cassandra are deployed ok such that you are able to collect metrics and view graphs in the console. Can you tell me what kinds of queries you are trying to run when you get the timeout. What tags, date ranges, etc.

**Comment by stobias123** [comment] 2017-02-23 03:41
Yes, metrics work fine within the openshift interface.

I'm not running any queries, just adding the data source and I get an error

**Comment by jsanda** [comment] 2017-02-23 03:48
Can you share the logs from your Hawkular Metrics and Cassandra pods? Cassandra should have a debug log file at /opt/apache-cassandra/logs/debug.log. If it is not too big, it would be helpful if you could share it.

**Comment by stobias123** [comment] 2017-02-23 03:55
**HAWKULAR POD** 

```
03:52:09,628 ERROR [org.hawkular.metrics.api.jaxrs.util.ApiUtils] (RxComputationScheduler-3) HAWKMETRICS200010: Failed to process request: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at rx.observable.ListenableFutureObservable$2$1.run(ListenableFutureObservable.java:78)
	at rx.observable.ListenableFutureObservable$1$1.call(ListenableFutureObservable.java:50)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
	at com.datastax.driver.core.exceptions.ReadTimeoutException.copy(ReadTimeoutException.java:115)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:124)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:471)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1070)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	... 1 more
Caused by: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:62)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:37)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:277)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:257)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 29 more
```

**CASSANDRA POD** 
```
INFO  15:42:03 Redistributing index summaries
INFO  16:42:03 Redistributing index summaries
INFO  17:13:00 ConcurrentMarkSweep GC in 338ms.  CMS Old Gen: 2812163104 -> 1203616208; Par Eden Space: 921824 -> 39842088; 
INFO  17:28:51 Saved KeyCache (623203 items) in 1448 ms
INFO  17:42:03 Redistributing index summaries
INFO  18:42:03 Redistributing index summaries
INFO  19:42:03 Redistributing index summaries
INFO  19:54:35 ParNew GC in 220ms.  CMS Old Gen: 2487195272 -> 2503105808; Par Eden Space: 335544320 -> 0; Par Survivor Space: 26802832 -> 25140896
INFO  20:32:32 ConcurrentMarkSweep GC in 303ms.  CMS Old Gen: 2825395560 -> 986689824; Par Eden Space: 50008 -> 19657992; 
INFO  20:41:06 ParNew GC in 494ms.  CMS Old Gen: 1038157840 -> 1054320568; Par Eden Space: 335544320 -> 0; Par Survivor Space: 26505280 -> 24987248
INFO  20:42:03 Redistributing index summaries
INFO  21:28:51 Saved KeyCache (588110 items) in 1495 ms
INFO  21:42:03 Redistributing index summaries
INFO  22:42:03 Redistributing index summaries
INFO  23:31:04 ParNew GC in 246ms.  CMS Old Gen: 2458397472 -> 2468434472; Par Eden Space: 335544320 -> 0; Par Survivor Space: 14949936 -> 17422536
INFO  23:42:04 Redistributing index summaries
INFO  00:15:18 ConcurrentMarkSweep GC in 386ms.  CMS Old Gen: 2811440896 -> 1228273896; Par Eden Space: 5326088 -> 21644128; 
INFO  00:41:56 ParNew GC in 296ms.  CMS Old Gen: 1441048768 -> 1456211560; Par Eden Space: 335544320 -> 0; Par Survivor Space: 23048800 -> 37671480
INFO  00:42:04 Redistributing index summaries
INFO  00:42:49 ParNew GC in 202ms.  CMS Old Gen: 1617380360 -> 1630953192; Par Eden Space: 335544320 -> 0; Par Survivor Space: 34594896 -> 31169280
INFO  01:28:51 Saved KeyCache (615310 items) in 1709 ms
INFO  01:42:04 Redistributing index summaries
INFO  02:42:04 Redistributing index summaries
INFO  02:57:47 ConcurrentMarkSweep GC in 258ms.  CMS Old Gen: 2822919928 -> 940695472; Par Eden Space: 898384 -> 36380136; 
INFO  03:42:04 Redistributing index summaries
INFO  03:52:19 ParNew GC in 246ms.  CMS Old Gen: 1537256272 -> 1543099928; Par Eden Space: 335544320 -> 0; Par Survivor Space: 27643296 -> 40563768
```

**Comment by jsanda** [comment] 2017-02-23 04:42
Unfortunately the log snippets do not provide enough detail. @jotak do you know what queries (if any) run when the data source is deployed and initialized?

**Comment by stobias123** [comment] 2017-02-23 05:48
I just realized I'm on grafana 4.1.1 and docs say this is for grafana 3. Could that be the cause?

**Comment by jotak** [comment] 2017-02-23 07:46
@jsanda the first call to the API by the datasource is GET on /hawkular/metrics/status , so it's probably not the problem. Then it performs GET on /hawkular/metrics/metrics with no parameters.

@stobias123 The datasource should be fine on Grafana 4. I haven't tested on 4.1.1 yet (I'll do it), but I'd be surprised Grafana would be the cause of this issue.
Can you open the javascript console (shift+ctrl+i in chrome/firefox) and tell us which request is failing/stalling under the "network" tab?

**Comment by jotak** [comment] 2017-02-23 07:50
@stobias123 , can you also check with curl?

```bash
curl -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
       -H "Hawkular-Tenant: YYYYY"
       -X GET https://hawkularserver/hawkular/metrics/metrics
```
with your openshift token, tenant and hawkular server

**Comment by stobias123** [comment] 2017-02-23 07:51
@jotak it falis here with a 500-> http://grafana-url/api/datasources/proxy/1/metrics

**Comment by stobias123** [comment] 2017-02-23 07:53
```
curl -H "Authorization: Bearer asdfasdfasdfasdf" \
       -H "Hawkular-Tenant: tenant" \
       -X GET https://metrics.domain.com/hawkular/metrics/metrics -k
```
returned nothing.

**Comment by stobias123** [comment] 2017-02-23 07:56
user@server# curl -H "Authorization: Bearer asdfasdfasdf" \
       -H "Hawkular-Tenant: tenant" \
       -X GET https://metrics.cloud.domain.com/hawkular/metrics/metrics -k
{"errorMsg":"Failed to perform operation due to an error: Cassandra timeout during read query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded)"}%                                                                                             stobias@cabmbd053862  ~ 

**Comment by jotak** [comment] 2017-02-23 07:59
Just a thought... maybe the error in hawkular-metrics logs is not related to this issue. Did you notice if it happens every time you try to test the datasource?

Also I remember that @burmanm fixed a bug on token authentication that ended in timeout on failure, or something like that ( https://github.com/hawkular/hawkular-metrics/pull/752 ). It might be the issue here, which would indicate that there's something wrong with your openshift token.

**Comment by stobias123** [comment] 2017-02-23 08:04
Yes it happens every time I save+test the datasource.

I tried token from both the hawkular service account and from the oauth/token/request. Would that mean I'm requesting token wrong or that I should update my hawkular pod?

**Comment by jotak** [comment] 2017-02-23 08:18
@stobias123 can you tell me if it works if you use the "hawkular" tenant (low case)? If so it's something related to permissions on projects ; I need to test on my side, it's been a while I didn't configure permissions... Meanwhile you can have a look to that blog post: http://www.hawkular.org/blog/2017/01/17/obst-hosa.html there are some chapters on authentication & service accounts with hawkular.

**Comment by jotak** [comment] 2017-02-23 08:37
Hum sorry, if the cassandra timeout is related to the curl command, then it's not an authentication issue, wrong track.

I can't reproduce the error on my side. The "best" I have is a 504 Gateway timeout error when I use an invalid token.

By the way, what's your version of hawkular-metrics? It's given on hawkular front page https://yourserver/hawkular/metrics

**Comment by stobias123** [comment] 2017-02-23 19:14
version of metrics is "0.23.4.Final"

**Comment by jsanda** [comment] 2017-02-23 19:21
@stobias123 Do you know how big your environment is in terms of number of pods? What configuration are you using for Cassandra in terms of CPU and RAM?

**Comment by stobias123** [comment] 2017-02-23 19:25
Pretty small, only like 27 pods. It's the default metrics install as of origin 1.3 - only one cassandra pod. It's got no limits or quota, hovering around 7GB of memory and 140millicore CPU

**Comment by mwringe** [comment] 2017-02-23 19:32
And you can view the graphs in the OpenShift console without any issue?

**Comment by stobias123** [comment] 2017-02-23 19:37
Yup, no problems in OS console.

@jotak I didn't see your tenant comment until now, I get "Forbidden" when using hawkular tenant.

Previously I'd been using project names as tenant. I can't recall where I read that but I thought that was correct.

**Comment by mwringe** [comment] 2017-02-23 19:41
> Previously I'd been using project names as tenant. I can't recall where I read that but I thought that was correct.

Yes, that is correct. The tenant corresponds to the project name.

This is a bit strange, since the console will be doing essentially the same command it is able to access the data being stored. 

The big difference is that the console is not using the /hawkular/metrics/metrics endpoint, but its accessing the metrics more directly.

@jsanda any ideas?

**Comment by stobias123** [comment] 2017-02-23 19:44
Ok so I added my account to the cluster-admin role, and I've got it to connect to hawkular tenant now, but using a project name for tenant still results in error.

Question about permissions though...
What are the minimum security policies I need to assign to a user for this to work?


Appreciate the responsiveness here, thanks to everyone.

**Comment by mwringe** [comment] 2017-02-23 19:51
There wont be a 'hawkular' tenant unless you created a project called 'hawkular' in OpenShift :)

> What are the minimum security policies I need to assign to a user for this to work?

You shouldn't have to do anything here. If your user can view pods in your project, then they can view the metrics corresponding to those pods.

The fact that you are getting an error message from Cassandra means that your user has permission, if they didn't have permission it would fail quickly with an access denied error.

There is something wrong with your Hawkular Metrics or Cassandra instances. Can you please attach logs somewhere from these? @jsanda should be able to help more.

**Comment by jsanda** [comment] 2017-02-23 19:54
@stobias123, This sounds like a bug in Hawkular Metrics. Would you mind opening a ticket at https://issues.jboss.org/projects/HWKMETRICS? In your Cassandra pod, run `nodetool setlogginglevel org.apache.cassandra DEBUG` and then try adding the data source again. After you get the error, please upload /opt/apache-cassandra/logs/debug.log* to the ticket. This will help me see what is failing.

**Comment by stobias123** [comment] 2017-02-23 21:58
https://issues.jboss.org/browse/HWKMETRICS-610

**Comment by pat2man** [comment] 2017-03-29 18:41
I've had issues like this when my Cassandra pods' resource limits were set too low. Too many data points causes timeouts all over. Increasing the limits I can get it to work most of the time.

**Comment by jotak** [comment] 2017-07-21 12:37
Closing here as it is related to resource limits and ticket https://issues.jboss.org/browse/HWKMETRICS-610 is opened for server side

**Closed by jotak** 2017-07-21 12:37 UTC

**Comment by arnaudlemaignen** [comment] 2017-08-30 15:19
Hi all
Do we have news on this issue? The bug is still open but discussion is closed.
I have exactly the same issue using Grafana 4.1.2+Hawkular 0.23.8 in an Openshift env.
Increasing the memory limit did not helped.

Thanks

**Comment by jotak** [comment] 2017-08-30 15:35
Hi @arnaudlemaignen ,
When you say you have the exact same error, do you mean Cassandra read timeout ? (message "Caused by: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query ..." in hawkular pod logs)
Can you provide hawkular and cassandra pods logs?
